- Gemfile
- Gemfile.lock
- app/assets/javascripts/fulcrum.js
- app/assets/javascripts/views/task_form.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/screen.scss
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/flash_helper.rb
- app/views/admin/users/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flash.html.erb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
- app/views/users/refresh_user_list.js.erb
- spec/controllers/users_controller_spec.rb
* Added form errors
* Allow picking existents users
* Downgraded jQuery version to make it compatible with jquery-rails
* Improved flash rendering
> Improve users form

- app/assets/javascripts/application.js
- app/assets/javascripts/views/form_view.js
- app/assets/javascripts/views/note_form.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/users.scss
- app/views/projects/_attachinary_template.html
- app/views/projects/show.html.erb
- spec/javascripts/views/story_view_spec.js
Adjusting the Story form:
- better file upload behavior (progress bar, warning message to save the story)
- changing some sections to make more sense (putting tasks right after description)
- removing the 'edit' button: now clicking on the description text itself opens the textarea
cc @adbatista @daniloisr @talyssonoc @macedo
> Adjusting upload view

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/views/note_form.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/application.scss
- app/services/note_creation_service.rb
- app/views/projects/show.html.erb
Adding the UI bits to description and notes textarea.
@daniloisr @adbatista @talyssonoc 
on 🔥  !
> Username auto-complete with "@" trigger

- app/controllers/integrations_controller.rb
- app/views/integrations/_form.html.erb
- app/views/integrations/index.html.erb
- app/views/projects/_form.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/new.html.erb
- spec/controllers/integrations_controller_spec.rb
> Improve "Integrations" form

- app/assets/javascripts/views/project_view.js
- app/views/notifications/accepted.text.erb
- app/views/notifications/delivered.text.erb
- app/views/notifications/new_note.text.erb
- app/views/notifications/rejected.text.erb
- app/views/notifications/started.text.erb
- app/views/notifications/story_mention.text.erb
- app/views/projects/show.html.erb
@talyssonoc @adbatista @daniloisr
> Story link

- app/assets/javascripts/models/note.js
- app/assets/javascripts/models/story.js
- app/assets/javascripts/models/task.js
- app/assets/javascripts/templates/note.jst.ejs
- app/assets/javascripts/templates/task.jst.ejs
- app/assets/javascripts/views/note_view.js
- app/assets/javascripts/views/story_view.js
- app/models/note.rb
- app/models/story.rb
- app/models/task.rb
- spec/javascripts/models/story_spec.js
- spec/models/note_spec.rb
- spec/models/story_spec.rb
- spec/models/task_spec.rb
Notes, tasks and attachments should also be frozen.
Adjustments must be new stories.
> Accepted stories can't change.

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/projects_controller.rb
- app/helpers/projects_helper.rb
- app/models/iteration.rb
- app/models/story.rb
- app/services/iteration_service.rb
- app/views/projects/_nav.html.erb
- app/views/projects/reports.html.erb
- config/locales/de.yml
- config/locales/el.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/ja.yml
- config/locales/nl.yml
- config/locales/pt-BR.yml
- config/routes.rb
- spec/models/iteration_spec.rb
- spec/services/iteration_service_spec.rb
Adding initial support for a Reports page for the Project
- adding the same iteration calculation from the javascript side (including same specs to make sure)
- adding an iteration service class to group reports calculation
- adding chart_kick as an initial attempt for simple graphs
- velocity per iteration
- bugs/chores quantity per iteration
- velocity per member per iteration
@daniloisr @adbatista @macedo @talyssonoc
> Iteration report

- .gitignore
- app/assets/javascripts/application.js
- app/assets/javascripts/locales.js.erb
- app/assets/javascripts/templates/story.jst.ejs
- app/assets/javascripts/views/form_view.js
- app/assets/javascripts/views/note_form.js
- app/assets/javascripts/views/story_view.js
- app/views/admin/users/index.html.erb
- app/views/registrations/edit.html.erb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
- config/application.rb
- config/locales/de.yml
- config/locales/el.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/ja.yml
- config/locales/nl.yml
- config/locales/pt-BR.yml
Almost there with translations, I guess all of the most important are covered here now.
> Missing translations

- app/assets/javascripts/application.js
- app/assets/javascripts/views/project_velocity_override_view.js
- app/assets/stylesheets/simple-sidebar.scss
- app/views/layouts/application.html.erb
- spec/features/stories_spec.rb
> Adjusting sidebar

- app/models/story.rb
- app/operations/story_operations.rb
- app/presenters/activity_presenter.rb
- app/views/projects/_activities_group.html.erb
- fixtures/vcr_cassettes/cloudinary_upload_activity.yml
- spec/operations/story_operations_spec.rb
- spec/presenters/activity_presenter_spec.rb
And properly presenting the changes in the activity feed.
> Tracking attachinary documents changes

- Gemfile
- Gemfile.lock
- app/helpers/projects_helper.rb
- app/models/project.rb
- app/services/iteration_service.rb
- app/views/projects/_nav.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/reports.html.erb
- config/locales/de.yml
- config/locales/el.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/ja.yml
- config/locales/nl.yml
- config/locales/pt-BR.yml
- spec/services/iteration_service_spec.rb
> Layout improvements in the reports page.

- app/services/iteration_service.rb
- spec/services/iteration_service_spec.rb
standard_deviation was returning Nan, when groups = 0
> fix std deviation

- Gemfile
- app/assets/stylesheets/screen.scss
> small layout fixes

- Gemfile.lock
- app/controllers/projects_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.erb
- app/views/registrations/edit.html.erb
- app/workers/import_worker.rb
- spec/controllers/projects_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/factories.rb
- spec/rails_helper.rb
- spec/services/iteration_service_spec.rb
- spec/workers/import_worker_spec.rb
If the project's start date is more recent than the accepted_at in the stories, the project show page errors out, so fixing in the import procedure. Algo doing some refactoring and adding missing specs.
> Improving csv import

- app/operations/story_operations/state_change_notification.rb
Because actor for notification is nil
> Sometimes changing story status raises a 500 error

- Procfile
- app.json
- config/sidekiq.yml
- db/seeds.rb
* Sidekiq concurrency must be configurable via env vars to make it runnable on free redis addon
* Add missing team setup to seeds.rb
> Enable Heroku review apps

- app/controllers/application_controller.rb
https://rollbar.com/cm-fulcrum/cm-fulcrum/items/29/
> Checks for empty string when setting the team

- app/controllers/users_controller.rb
- app/views/admin/users/edit.html.erb
- spec/controllers/users_controller_spec.rb
https://central.cm42.io/projects/cm-fulcrum#story-15704
> Allow admin to remove user from any team's project

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/screen.scss
- app/assets/stylesheets/simple-sidebar.scss
- app/helpers/sidebar_helper.rb
- app/views/admin/users/edit.html.erb
- app/views/application/_sidebar.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/_nav.html.erb
- app/views/projects/edit.html.erb
- app/views/users/index.html.erb
> Improve Sidebar

- Gemfile.lock
- app/controllers/users_controller.rb
- app/views/admin/users/_form.html.erb
- config/locales/de.yml
- config/locales/el.yml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/ja.yml
- config/locales/nl.yml
- config/locales/pt-BR.yml
> Adding a way to edit the user’s role in the admin/users form

- app/views/projects/_nav.html.erb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
Show a simple list of project members for non-admin users.
Closes #56
> Show project members to non-admin members

- app/assets/stylesheets/screen.scss
> Fix word break in story title

- app/assets/javascripts/views/story_view.js
- spec/javascripts/views/story_view_spec.js
This PR:
* Create two functions callbacks for 2 events: Click button save and done attachment upload.
* Removes the visual feedback to save the story, since it isn't necessary
> Attachment automatically saved when done.

- app/controllers/admin/users_controller.rb
- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/teams_controller.rb
- app/models/user.rb
- app/operations/team_operations.rb
- app/policies/project_policy.rb
- app/policies/team_policy.rb
- app/views/application/_sidebar.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.erb
- app/views/registrations/new.html.erb
- app/views/teams/edit.html.erb
- app/views/teams/index.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- config/routes.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/controllers/teams_controller_spec.rb
- spec/features/confirmations_spec.rb
- spec/features/logins_spec.rb
- spec/features/teams_spec.rb
- spec/policies/team_policy_spec.rb
- spec/support/integration_helpers.rb
This PR Remove the team slug field from sign in, sign up and forgot password forms and move the "Create new Team" button to a new page where the users can select or create a team. https://github.com/Codeminer42/cm42-central/issues/66
> Login sequence

- app/controllers/application_controller.rb
- app/controllers/locales_controller.rb
- app/controllers/teams_controller.rb
Redirect to teams page when the session expire and the remember token is activated.
> Redirect to teams page when current_team is blank

- app/helpers/topbar_helper.rb
- app/views/layouts/application.html.erb
Fix the projects listing from top bar menu.
> Fix projects list from top bar menu

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_card.scss
- app/assets/stylesheets/_members.scss
- app/assets/stylesheets/_screen.scss
- app/assets/stylesheets/_timeline.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/application.scss
- app/controllers/projects_controller.rb
- app/views/projects/_activities_group.html.erb
- app/views/projects/_project.html.erb
- app/views/projects/index.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/features/projects_spec.rb
> Projects redesign

- app/assets/javascripts/views/story_view.js
- spec/javascripts/views/story_view_spec.js
> Fix new story attachment bug

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_card.scss
- app/assets/stylesheets/_screen.scss
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/users_helper.rb
- app/models/user.rb
- app/views/projects/_project.html.erb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
> Manage members redesign

- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/_members.scss
- app/assets/stylesheets/_screen.scss
- app/assets/stylesheets/_user-profile.scss
- app/assets/stylesheets/application.scss
- app/views/projects/_project.html.erb
- app/views/registrations/_form.html.erb
- app/views/registrations/edit.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
> Edit profile redesign

- README.md
> Fix Markdown syntax on README

- CHANGELOG.md
- app/assets/stylesheets/_screen.scss
- app/controllers/teams_controller.rb
- app/views/teams/_form.html.erb
- app/views/teams/edit.html.erb
- config/locales/en.yml
> Edit team redesign

- app/api/entities/project.rb
- app/api/entities/project_analysis.rb
- app/api/v1/projects.rb
- spec/api/entities/project_analysis_spec.rb
- spec/api/v1/projects_spec.rb
Iteration service did not return the data correctly when used to gem center-support
> Fix iteration service to use in central-bot project

- CHANGELOG.md
- app/api/v1/base_api.rb
- app/api/v1/users.rb
- app/models/user.rb
- spec/api/v1/users_spec.rb
Add endpoint to get information about users.
> Add User endpoint to API

- CHANGELOG.md
- app/controllers/admin/users_controller.rb
- app/presenters/admin/user_presenter.rb
- app/views/admin/users/_actions.html.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/index.html.erb
- spec/presenters/admin/user_presenter_spec.rb
Refactor the admin/users views which was discussed on PR #117.
> Refactor admin/users views using a Presenter

- CHANGELOG.md
- app/api/entities/project.rb
- app/api/entities/story.rb
- app/api/entities/team.rb
- app/api/entities/user.rb
- app/api/v1/projects.rb
- app/models/note.rb
- app/models/story.rb
- app/models/user.rb
- app/operations/story_operations/legacy_fixes.rb
- app/presenters/activity_presenter.rb
- lib/tasks/fulcrum.rake
- lib/tasks/i18n_missing_keys.rake
- spec/models/story_spec.rb
🚧  Some improvements to fix some issues reported by codeclimate.
> General improvements

- CHANGELOG.md
- app/assets/javascripts/collections/activity_collection.js
- app/assets/javascripts/models/activity.js
- app/assets/javascripts/models/story.js
- app/assets/javascripts/models/user.js
- app/assets/javascripts/templates/activity.ejs
- app/assets/javascripts/templates/project_view.ejs
- app/assets/javascripts/views/column_view.js
- app/assets/javascripts/views/history_view.js
- app/assets/javascripts/views/project_view.js
- app/assets/javascripts/views/story_view.js
- app/assets/javascripts/views/task_form.js
- app/assets/stylesheets/_navbar.scss
- app/assets/stylesheets/_screen.scss
- app/controllers/stories/activities_controller.rb
- app/models/activity.rb
- app/policies/activity_policy.rb
- app/policies/story_policy.rb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- config/routes.rb
- spec/controllers/stories/activities_controller_spec.rb
- spec/factories.rb
- spec/javascripts/models/activity_spec.js
- spec/javascripts/models/note_spec.js
- spec/javascripts/models/task_spec.js
- spec/javascripts/views/story_view_spec.js
- spec/models/activity_spec.rb
- vendor/assets/javascripts/backbone.rails.js
Creates a new column on a Project's board to host a HistoryView for a story. #72
> Add a History view for a Story

- CHANGELOG.md
- Gemfile.lock
This PR updates the central-support gem to fix issues with project volatility.
> Update Central-Support gem

- CHANGELOG.md
- app/controllers/application_controller.rb
- spec/features/logins_spec.rb
- spec/support/integration_helpers.rb
https://github.com/Codeminer42/cm42-central/issues/142
> Set current_team automatically when user has only one team

- CHANGELOG.md
- app/assets/javascripts/components/story/StoryControls.js
- app/assets/javascripts/views/story_view.js
https://github.com/Codeminer42/cm42-central/issues/138
> Add react component to story controls

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/assets/javascripts/components/projects/ProjectCard.js
- app/assets/stylesheets/_card.scss
- app/assets/stylesheets/_screen.scss
- app/models/project.rb
- app/models/tag_group.rb
- app/models/team.rb
- app/presenters/project_presenter.rb
- app/serializers/project_serializer.rb
- db/migrate/20170329211205_create_tag_groups.rb
- db/migrate/20170329220454_add_tag_group_id_to_project.rb
- db/schema.rb
- package.json
- spec/factories.rb
- spec/features/projects_spec.rb
- spec/javascripts/components/projects/project_card_spec.js
- spec/presenters/project_presenter_spec.rb
- spec/serializers/project_serializer_spec.rb
> Project Grouping By Tag

- CHANGELOG.md
- app/controllers/users_controller.rb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
- app/views/users/refresh_user_list.js.erb
When adding or removing users to a project the list didn't refresh correctly, this fixes the problem.
> Fix refresh_user_list

- CHANGELOG.md
- README.md
- docker-compose.yml
Updates docker-compose file.
It has been added a missing ENV param. node_modules folder is now a Docker volume. 
It was missing the step to install npm dependencies on README.md file.
PS: This is my first pull request ever. So.. be patient :)
> Fix docker setup

- CHANGELOG.md
- The option to each project has its own tag group
- Links to stories within the same project can be added to a story description.
- Docker setup for development env.
- User list refreshing when adding or removing team members
> Release v1.3

- CHANGELOG.md
- Gemfile.lock
- app/assets/javascripts/app.js
- app/assets/javascripts/components/tag_groups/ColorPicker.js
- app/assets/javascripts/controllers/tag_groups/TagGroupsController.js
- app/assets/stylesheets/_color-picker.scss
- app/assets/stylesheets/_tag-group.scss
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/application.scss
- app/controllers/projects_controller.rb
- app/controllers/tag_groups_controller.rb
- app/helpers/projects_helper.rb
- app/models/tag_group.rb
- app/policies/tag_group_policy.rb
- app/views/projects/_form.html.erb
- app/views/projects/index.html.erb
- app/views/tag_groups/_form.html.erb
- app/views/tag_groups/edit.html.erb
- app/views/tag_groups/index.html.erb
- app/views/tag_groups/new.html.erb
- app/views/tag_groups/show.js.erb
- config/locales/en.yml
- config/locales/pt-BR.yml
- config/routes.rb
- package.json
- spec/features/projects_spec.rb
- spec/models/tag_group_spec.rb
- spec/policies/tag_group_policy_spec.rb
> Tag group form

- CHANGELOG.md
- app/presenters/admin/user_presenter.rb
- spec/presenters/admin/user_presenter_spec.rb
> Fix issue #167 about admin assignment

- CHANGELOG.md
- README.md
- config/fulcrum.rb
The config file will always read false, it's missing reading from the ENV first.
> Disable registration from ENV

- CHANGELOG.md
- app/assets/javascripts/components/story/StoryHistoryLocation.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_icons.scss
- spec/features/stories_spec.rb
Refactor Story's location and history `.input-form-group` into a React Component.
> Add react component to story history, id and location clipboard

- CHANGELOG.md
- app/assets/stylesheets/_tagit.scss
- app/assets/stylesheets/application.scss
- vendor/assets/stylesheets/jquery_tagit.css
- fixes #132
- add basic style for Labels
> Fix labels autocomplete overflowing

- CHANGELOG.md
- tag group form
- Added First time tour.
- Basic style for Labels
- Slack Support
- Release date to Story
- Project now uses yarn 
- Story id, location and history input-form-group into a react component
- Story estimate select into a react component
- The attributes of a release story when creating or editing
- Remove the API module used in `using` params into Project Entity
- Clean up DatabaseCleaner config
- Admin assignment
- 'Velocity per member' report title translation
- Disable registration using enviroment variable `DISABLE_REGISTRATION`
- Display of throbber animated gif when adding a note or a task
- Labels autocomplete overflow
> [1.4.0] - 2017-05-23

- app/assets/javascripts/components/story/StorySelect.js
- app/assets/javascripts/views/story_view.js
* Makes "blank" option optional in the StorySelect component;
* Add className to StorySelect;
* Refactor StorySelect render to create array with its options.
> Makes StorySelect generic

- CHANGELOG.md
- app/assets/javascripts/components/story/StorySelect.js
- app/assets/javascripts/views/story_view.js
*Refactor story-type-select to use the generic select component.
> Use the generic StorySelect to render story type select.

- CHANGELOG.md
- app/assets/javascripts/views/story_view.js
*Refactor story-state-select to use the generic select component.
> Use generic StorySelect to render story state select

- README.md
> Added missing instructions at README

- CHANGELOG.md
- app/assets/javascripts/views/story_view.js
Create renderSelects function
Add changes to CHANGELOG
> Refactor renderReactComponents function

- CHANGELOG.md
- app/assets/javascripts/components/jquery_wrappers/TaggedInput.js
- app/assets/javascripts/components/story/StoryLabels.js
- app/assets/javascripts/views/story_view.js
* Create StoryLabels component
* Wrap Tagit into react component
> StoryLabels to react component

- CHANGELOG.md
- docker-compose.yml
- package.json
Adding `--public webpack`to `docker-compose.yml` to fix #199 problem.
> Fixing docker-compose webpack compatibility

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/policies/user_policy.rb
- spec/policies/user_policy_spec.rb
Alter action update in user policy, the user only edit and update about himself
> Fix permission to update others users - related issue #191

- CHANGELOG.md
- app/assets/javascripts/components/description/DescriptionContent.js
- app/assets/javascripts/components/jquery_wrappers/AtWhoInput.js
- app/assets/javascripts/components/jquery_wrappers/TaggedInput.js
- app/assets/javascripts/components/story/StoryDescription.js
- app/assets/javascripts/views/story_view.js
- spec/javascripts/components/story/story_description_spec.js
- spec/javascripts/views/story_view_spec.js
* Create AtWhoInput to wrap jquery atwho.
* Fully converts Story Description to react component
> Story description to react component

- CHANGELOG.md
- Gemfile.lock
- app.json
- app/operations/story_operations/state_change_notification.rb
- app/views/integrations/_discord.html.erb
- app/workers/integration_worker.rb
- spec/controllers/integrations_controller_spec.rb
- spec/operations/story_operations_spec.rb
It will enable discord webhook integration support
> Enable discord integration

- .codeclimate.yml
- CHANGELOG.md
- app/admin/enrollment.rb
- app/admin/ownership.rb
- app/admin/team.rb
- app/admin/user.rb
- app/controllers/memberships_controller.rb
- app/controllers/teams_controller.rb
- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/services/project_enroller_service.rb
- app/services/project_membership_enroller_service.rb
- app/views/teams/edit.html.erb
- app/views/teams/new_enrollment.html.erb
- app/views/users/_user_list.html.erb
- app/views/users/index.html.erb
- app/views/users/refresh_user_list.js.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- config/routes.rb
- spec/controllers/memberships_controller_spec.rb
- spec/controllers/teams_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/features/projects_spec.rb
- spec/features/teams_spec.rb
- spec/services/project_enroller_service_spec.rb
- spec/services/project_membership_enroller_service_spec.rb
Remove users/form inside projects and permited associate user in project.
Before:
After:
Also I adjusted the translation user_not_found
> Remove users/form inside projects

- .rubocop.yml
- CHANGELOG.md
- app/controllers/memberships_controller.rb
- app/helpers/projects_helper.rb
- app/operations/note_operations.rb
- app/operations/story_operations.rb
- app/services/burn_up_calculator.rb
- app/services/service.rb
- spec/services/burn_up_calculator_spec.rb
I will fix the rest of excluded files in separated PRs
> Enables rubocop Metrics/AbcSize

- CHANGELOG.md
- app/admin/project.rb
- app/api/entities/project.rb
- app/controllers/projects_controller.rb
- app/views/projects/_form.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- db/migrate/20170825181646_add_mail_reports_to_projects.rb
- db/schema.rb
- spec/api/entities/project_spec.rb
- spec/controllers/projects_controller_spec.rb
- spec/features/projects_spec.rb
This PR add flag into the project to admin start/stop interation mail reports.
> Add flag mail_report into the project.

- CHANGELOG.md
- app/api/v1/projects.rb
- spec/api/v1/projects_spec.rb
> Fix strong parameters into API.

- CHANGELOG.md
- app/controllers/application_controller.rb
- config/initializers/active_admin.rb
- config/initializers/devise.rb
[#18160](https://central.cm42.io/projects/central#story-18160)
> Fix central manage login and logout bugs.

- CHANGELOG.md
- Gemfile.lock
- db/migrate/20170914172941_add_delivered_at_to_stories.rb
- db/schema.rb
https://github.com/Codeminer42/cm42-central/issues/57
> Update cm42-central-support version to save delivered_at

- CHANGELOG.md
- app/helpers/projects_helper.rb
- app/services/burn_down_calculator.rb
- app/views/projects/reports.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/services/burn_down_calculator_spec.rb
> Add Burn Down chart

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/admin/user.rb
- app/models/admin_user.rb
- app/views/layouts/application.html.erb
- app/views/user_impersonate/_header.html.erb
- config/initializers/user_impersonate.rb
- config/routes.rb
Add [user_impersonate2](https://github.com/rcook/user_impersonate2) gem for debugging purposes.
`manage/users`
> Add user impersonate gem

- CHANGELOG.md
- app/assets/javascripts/views/story_view.js
- app/controllers/stories_controller.rb
> Fix error returning to stories save

- CHANGELOG.md
- app/assets/stylesheets/_card.scss
- app/assets/stylesheets/_menu.scss
- app/assets/stylesheets/_overrides.scss
- app/assets/stylesheets/_simple-sidebar.scss
- app/views/users/_user_list.html.erb
Fix minor design details in the UI. In accord with the issue #200 
| Before | After |
| :-----------: | :-----------: |
| ![](https://i.gyazo.com/feceb66880a2f31ff6a7633e3d4d70f3.png) | ![](https://i.gyazo.com/b4bf3610c33ecb6ef1a870c58a4c94fb.png) |
> Minor UI adjustments. 

- CHANGELOG.md
- app/assets/javascripts/views/story_view.js
Fix an issue preventing story attachments from being properly uploaded and displayed.
> Fixes the attachment not showing, after uploaded.

- CHANGELOG.md
- app/assets/stylesheets/_screen.scss
- Lowered the spacing between the numbers and make the text bolder,
facilitating the visualization.
> Style estimation form

- CHANGELOG.md
- app/assets/javascripts/templates/story.ejs
- spec/features/stories_spec.rb
- Fixed bug where the form to estimate a task was not shown.
- Added a feature test to ensure this bug will not occur again.
> Show form to estimate a task

- CHANGELOG.md
- app/assets/javascripts/views/project_search_view.js
Prevent previous searched stories from appearing on new search results.
> Fix search duplication

- CHANGELOG.md
- app/assets/javascripts/components/story/StoryHistoryLocation.js
- app/assets/javascripts/views/story_view.js
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/features/stories_spec.rb
Add the ability to clone stories as per suggested on #256, that way creating a new story which mirrors the attributes of the source story.
> Adds the option to clone a story.

- CHANGELOG.md
- Gemfile.lock
- spec/workers/import_worker_spec.rb
Fixes https://github.com/Codeminer42/cm42-central/issues/292
> BUMP central-support to fix the story cache_names bug when owed_by was removed

- CHANGELOG.md
- config/webpack/configuration.js
- config/webpack/development.js
- config/webpack/shared.js
- config/webpacker.yml
> Fix webpack dev server on Windows

- CHANGELOG.md
- app/assets/javascripts/views/story_view.js
> fixes the highlight of searched stories

- CHANGELOG.md
- app/assets/javascripts/global_listeners.js
- app/assets/javascripts/views/story_view.js
Remove auto scroll from add story method
Add highlight function for when a story be saved
> Fix a bug in story creation

- .gitignore
- CHANGELOG.md
- app/assets/javascripts/components/story/StoryStateButtons.js
- app/assets/javascripts/templates/story.ejs
- app/assets/javascripts/views/story_view.js
- package.json
- spec/features/stories_spec.rb
- spec/javascripts/views/story_view_spec.js
Refs #183
- Isolated state buttons in a react component.
- Changed story.ejs to render an element to serve as a target.
- Changed story_view.js to replace the target element with the rendered
react component.
> Moved state buttons to a react component.

- CHANGELOG.md
- config/environments/development.rb
- docker-compose.yml
- When you start docker-compose and try do a import from a csv file, this action is freeze your action, because worker dont finded the memcached, so now this problemn is solved.
- You can see if my ENV is ok, my intetion is this way work local and docker without the user do some modification in code.
> Fix docker

- CHANGELOG.md
- app/assets/javascripts/components/story/StoryAttachment.js
- app/assets/javascripts/models/story.js
- This is one way to stay with [{}] and to verify utilize a function, I believe that have better way, but this one possibility solution without affect the system.
- I believe that no, because the array is small, and this verification only is trigger when the user click in some story.
> added function js to verify if files exist

- CHANGELOG.md
- app.json
- app/assets/javascripts/collections/story_collection.js
- app/assets/javascripts/models/attachmentOptions.js
- app/assets/javascripts/views/project_view.js
- app/assets/javascripts/views/story_view.js
- spec/javascripts/models/attachment_options_spec.js
- spec/javascripts/views/story_view_spec.js
- Remove some trigger to call every action in story to call signature.
- I believe that all is correct, but is good see if upload of files don't broken is some way.
> remove trigger for all time call signature

- CHANGELOG.md
- New way to load past stories
- New route to destroy batch stories.
- Missing button titles in story component
- CVE-2018-1000119 issue, updating rack-protection gem
- CVE-2018-8048 issue, updating loofah gem
> Update Changelog to v1.19

- CHANGELOG.md
- Remove Velocity / Volatility from ProjectCard to optimize performance
> Release v1.20.1

- CHANGELOG.md
- Fix stories in the done sprints
> Update changelog to v1.21.1

- app/assets/javascripts/actions/projectBoard.js
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/stories/Sprints.js
- app/assets/javascripts/reducers/columns/done.js
- app/assets/javascripts/reducers/project.js
- spec/javascripts/index.js
- spec/javascripts/polyfills/objectAssign.js
- spec/javascripts/reducers/column_done_spec.js
[Task link](https://central.cm42.io/projects/central-board-v2#story-20048)
> Show sprints in done column

- CHANGELOG.md
- app/assets/javascripts/controllers/projects/EditController.js
- app/controllers/projects_controller.rb
- app/javascript/packs/app.js
- app/views/projects/_delete_confirmation.html.erb
- app/views/projects/_form.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/new.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/controllers/projects_controller_spec.rb
- spec/features/projects_spec.rb
- Add a feature for user type the name of the project to confirm the deletion. (https://central.cm42.io/projects/central#story-19833)
> Project delete confirmation

- app/assets/javascripts/components/story/StoryItem.js
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/components/story/story_actions_spec.js
- spec/javascripts/components/story/story_points_spec.js
- spec/javascripts/components/story/story_state_button_spec.js
- spec/javascripts/views/story_view_spec.js
The action state button was hardcoded, but now it changes according
to the story state.
> Add Action State Button to the StoryItem

- spec/features/keycut_spec.rb
Bugfix: https://central.cm42.io/projects/central#story-19965
> Intermittent shortcut test

- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/CollapsedStory/CollapsedStoryEstimate.js
- app/assets/javascripts/components/story/CollapsedStory/index.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryControls.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryHistoryLocation.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/components/story/StoryItem.js
- app/assets/javascripts/components/story/StoryUrl.js
- app/assets/javascripts/models/beta/projectBoard.js
- app/assets/javascripts/reducers/columns/backlog.js
- app/assets/javascripts/reducers/columns/chillyBin.js
- app/assets/javascripts/reducers/columns/done.js
- app/assets/javascripts/reducers/story.js
- app/assets/stylesheets/new_board/_screen.scss
- app/assets/stylesheets/new_board/_story.scss
- package.json
- spec/javascripts/components/story/collapsed_story/collapsed_story_estimate_spec.js
- spec/javascripts/components/story/collapsed_story/collapsed_story_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_spec.js
- spec/javascripts/components/story/story_item_spec.js
- spec/javascripts/reducers/column_backlog_spec.js
- spec/javascripts/reducers/column_chillyBin_spec.js
- spec/javascripts/reducers/column_done_spec.js
- spec/javascripts/support/factories/storyFactory.js
- yarn.lock
Ref: [#story-22724](https://central.cm42.io/projects/central-board-v2#story-22724)
Expand a Story: 
Copy Story URL to clipboard:
> Feature/ Expand a story and copy story url in board V2

- CHANGELOG.md
- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryEstimate.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryType.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/stories.js
- app/assets/javascripts/reducers/story.js
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/components/story/expanded_story/expanded_story_estimate_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_type_spec.js
- spec/javascripts/components/story/story_item_spec.js
- spec/javascripts/reducers/stories_spec.js
This PR is for this two features: 
Estimate option: [22718](https://central.cm42.io/projects/central-board-v2#story-22718)
Story Type: [22717](https://central.cm42.io/projects/central-board-v2#story-22717)
> Feature: expandend story estimate and type (V2).

- README.md
Change out of date link in README (line 93-94)
> Change out of date link for rails in README

- app/assets/javascripts/models/beta/projectBoard.js
- app/models/note.rb
- app/models/task.rb
- spec/models/note_spec.rb
- spec/models/task_spec.rb
> Serialize in the correct format

- config/locales/pt-BR.yml
https://github.com/Codeminer42/cm42-central/issues/424
> Add Portuguese translation for new team instruction

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryTitle.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- spec/javascripts/components/story/expanded_story/expanded_story_title_spec.js
Add the component Title on Stories
> Add a component title

- CHANGELOG.md
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryState.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/models/beta/story.js
- spec/javascripts/components/story/expanded_story/expanded_story_state_spec.js
Ref: [#22719](https://central.cm42.io/projects/central-board-v2#story-22719)
> Create option to select expanded story state in board V2 

- CHANGELOG.md
- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/note.js
- app/assets/javascripts/components/Markdown.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryNotes.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/components/story/note/Note.js
- app/assets/javascripts/components/story/note/NotesList.js
- app/assets/javascripts/models/beta/note.js
- app/assets/javascripts/reducers/stories.js
- app/assets/javascripts/store/index.js
- app/assets/stylesheets/new_board/_screen.scss
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/actions/note_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_notes_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_spec.js
- spec/javascripts/components/story/note/note_spec.js
- spec/javascripts/components/story/note/notes_list_spec.js
Ref: [#22728](https://central.cm42.io/projects/central-board-v2#story-22728)
> Create option to create/delete notes in board V2

- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- app/views/projects/_form.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- db/seeds.rb
- spec/controllers/projects_controller_spec.rb
- spec/factories/project_factory.rb
- spec/features/projects_spec.rb
- spec/policies/project_policy_spec.rb
Also making it so when you archive a project you get redirected to the projects page instead of the archived project.
> Fix for unarchiving projects

- README.md
> adds landpage link on readme

- config/locales/es.yml
> Add Spanish translation for velocity strategy

- config/locales/es.yml
[#425](https://github.com/Codeminer42/cm42-central/issues/425)
> Add spanish release_date

- .env.sample
- CHANGELOG.md
- app.json
- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/attachment.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryAttachments.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/components/story/attachment/Attachment.js
- app/assets/javascripts/components/story/attachment/AttachmentList.js
- app/assets/javascripts/models/beta/attachment.js
- app/assets/javascripts/models/beta/attachmentUrl.js
- app/assets/javascripts/models/beta/fileUpload.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/stories.js
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/new_board/_story.scss
- app/controllers/stories_controller.rb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- package.json
- spec/javascripts/actions/attachment_spec.js
- spec/javascripts/actions/story_spec.js
- spec/javascripts/components/story/expanded_story/attachment/attachment_list_spec.js
- spec/javascripts/components/story/expanded_story/attachment/attachment_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_attachments_spec.js
- spec/javascripts/index.js
- spec/javascripts/models/beta/attachment_spec.js
- yarn.lock
Ref: [#22727](https://central.cm42.io/projects/central-board-v2#story-22727)
> Feature expanded story files

- config/initializers/csv_renderer.rb
> Fix export csv error when there are no stories in the projects

- app/assets/javascripts/actions/note.js
- app/assets/javascripts/actions/task.js
- app/assets/javascripts/models/beta/note.js
- app/assets/javascripts/models/beta/task.js
It was making the app behave in an unexpected way when the request failed.
> Move error handling to the correct place

- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/note.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/actions/task.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryAttachments.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/models/beta/attachment.js
- app/assets/javascripts/models/beta/note.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/models/beta/task.js
- app/assets/javascripts/reducers/stories.js
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/actions/note_spec.js
- spec/javascripts/actions/story_spec.js
- spec/javascripts/actions/task_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_spec.js
- spec/javascripts/models/beta/attachment_spec.js
- spec/javascripts/models/beta/story_spec.js
During the update all the fields in the story can't be clicked. Also there's a loading icon during the update in the cursor that the screen recording didn't show it.
> Added loading state to expanded story when updated

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryControls.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/javascripts/components/story/expanded_story/expanded_story_controls_spec.js
> Added a warning window when clicking on 'cancel' on an expanded story with unsaved changes

- app/models/project.rb
- app/models/team.rb
- spec/models/project_spec.rb
- spec/models/team_spec.rb
- Relates To [23748](https://central.cm42.io/projects/central#story-23748)
> Add block in slug when name have reserved word

- CHANGELOG.md
- app/api/v1/teams.rb
- spec/api/v1/teams_spec.rb
Rollbar: https://rollbar.com/cm-fulcrum/cm-fulcrum/items/319/
> Team user not found in api request

- CHANGELOG.md
- [ V2 ] Story:
- Stories can be updated when it's closed
- Block reserved words for new teams name
- Refactor `.csv` renderer
- Fix error in recaptcha when access page new team
- Fix team user not found in api request
> Update Changelog to v2.2.0

- CHANGELOG.md
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/stories/Sprint.js
- app/assets/javascripts/models/beta/iteration.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/selectors/backlog.js
- app/assets/javascripts/selectors/columns.js
- app/assets/javascripts/selectors/done.js
- spec/javascripts/models/beta/iteration_spec.js
- spec/javascripts/selectors/columns_spec.js
Fix bug of number, date and points of sprints on board V2 [#24016](https://central.cm42.io/projects/central-board-v2#story-24016)
Before:
After:
> Fix/ Sprint number, date and points.

- CHANGELOG.md
- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDefault/index.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryHistoryLocation.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryRelease/index.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/stories.js
- spec/javascripts/components/story/expanded_story/expanded_story_history_location_spec.js
- spec/javascripts/models/beta/story_spec.js
Create option to clone story on board V2 [#22726](https://central.cm42.io/projects/central-board-v2#story-22726)
> Feature/ clone story

- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/notifications.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/Notifications/Message.js
- app/assets/javascripts/components/Notifications/index.js
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/models/beta/notification.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/notifications.js
- app/assets/javascripts/store/index.js
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/new_board/_screen.scss
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- package.json
- spec/javascripts/actions/notifications_spec.js
- spec/javascripts/actions/story_spec.js
- spec/javascripts/components/notifications/message_spec.js
- spec/javascripts/components/notifications/notifications_spec.js
- spec/javascripts/models/beta/notification_spec.js
- spec/javascripts/models/beta/story_spec.js
- yarn.lock
Story: [#23389](https://central.cm42.io/projects/central-board-v2#story-23389)
> Feature/ Create notification system

- .travis.yml
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryEstimate.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryState.js
- app/assets/javascripts/models/beta/story.js
- config/karma.conf.js
- spec/javascripts/components/story/expanded_story/expanded_story_state_spec.js
- spec/javascripts/models/beta/story_spec.js
Added isUnestimatedFeature to check story and disable state, also some changes to isUnestimatedFeature function so it works in more estimate types
> Disable story state while "no estimate" is selected

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryState.js
- app/assets/javascripts/models/beta/story.js
- spec/javascripts/components/story/expanded_story/expanded_story_state_spec.js
- spec/javascripts/models/beta/story_spec.js
Added function to handle state changing based on estimate value
> Change state on estimated feature

- app/controllers/stories_controller.rb
- app/models/story.rb
- spec/controllers/stories_controller_spec.rb
- spec/models/story_spec.rb
Accept story tasks and notes when cloning them to be able to copy all the attributes of a story.
> Clone full story

- app/assets/javascripts/selectors/backlog.js
- app/assets/javascripts/selectors/columns.js
- spec/javascripts/selectors/columns_spec.js
Added unscheduled stories to orderByState selector and added orderByState in getColumns.
> Adding ordering to chilly bin column

- CHANGELOG.md
- spec/javascripts/selectors/done_spec.js
Tests for function mountPastIterations of done selector.
> Tests for done selector

- app/controllers/application_controller.rb
- app/controllers/beta/projects_controller.rb
- app/controllers/project_boards_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/stories_controller.rb
- app/models/user.rb
- app/operations/beta/project_board_operations.rb
- spec/controllers/projects_controller_spec.rb
- spec/controllers/stories_controller_spec.rb
- spec/operations/beta/project_board_operations_spec.rb
The user can now switch to the project of any other participating team.
> allow user switch project from another team

- spec/features/projects_spec.rb
This PR is trying to fix the broken tests in Travis Ci
> fix capybara tests

- CHANGELOG.md
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/projects/ProjectLoading.js
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/new_board/_project_board.scss
- spec/javascripts/components/projects/project_board_spec.js
Added spinner for when project is loading.
> Spinner loading project

- CHANGELOG.md
- app/assets/javascripts/components/story/StoryItem.js
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/components/story/story_item_spec.js
When story has state accepted, the background is green.
> Accepted story background

- app/models/integration.rb
- spec/models/integration_spec.rb
This pr is migrating the integration model tests, from cm42-central-support to cm42-central.
> Migrate integrations tests

- app/models/user.rb
- spec/models/user_spec.rb
This pr is migrating the User model tests, from cm42-central-support to cm42-central.
> Migrate user tests

- app/models/team.rb
- spec/models/team_spec.rb
This pr is migrating the Team model tests, from cm42-central-support to cm42-central.
> Migrate team tests

- CHANGELOG.md
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/CollapsedStory/CollapsedStoryStateActions.js
- app/assets/javascripts/components/story/ExpandedStory/index.js
- app/assets/javascripts/models/beta/story.js
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/javascripts/actions/story_spec.js
- spec/javascripts/models/beta/story_spec.js
When the state was changed in expanded story, had not a confirm dialog.
> Confirm change state

- app/models/project.rb
- fixtures/vcr_cassettes/cloudinary_upload_import_csv.yml
- spec/models/project_spec.rb
This pr is migrating the Project model tests, from cm42-central-support to cm42-central.
> Migrate Projects tests

- app/services/statistics.rb
- spec/services/statistics_spec.rb
This is the migrating the statistics class from cm42-central-support to cm42-central.
> Migrate statistics from support

- app/models/activity.rb
- app/validators/subject_changed_validator.rb
- spec/lib/exporters/stories_spec.rb
- spec/models/activity_spec.rb
- spec/operations/base_operations/activity_recording_spec.rb
- spec/operations/story_operations_spec.rb
- spec/presenters/activity_presenter_spec.rb
This pr is migrating the Activity model tests, from cm42-central-support to cm42-central.
> Migrate Activity tests

- app/models/story.rb
- app/validators/central_estimate_validator.rb
- app/validators/user_belongs_to_project_validator.rb
- spec/models/story_spec.rb
This is the migrating the story model from cm42-central-support to cm42-central.
> Migrate story tests

- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDescription/ExpandedStoryContentArea.js
- spec/javascripts/components/projects/project_board_spec.js
> Fix bug of loading in history

- app/assets/javascripts/components/search/SearchResults.js
Adds the close button on the SearchResult column.
> add close button on SearchResult

- CHANGELOG.md
- app/assets/stylesheets/new_board/_story.scss
This PR change font color of one accepted/release story. Preview:
> Change font color of story release and accepted

- app/assets/javascripts/components/Columns/ColumnItem.js
- app/assets/javascripts/components/Columns/index.js
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/search/SearchResults.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryHistoryLocation.js
- app/assets/javascripts/models/beta/story.js
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/javascripts/components/columns/column_item_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_history_location_spec.js
This PR add a close button to history column and add some translations that wasn't added already. Preview:
> Add close button to history column

- spec/javascripts/reducers/pastIterations_spec.js
Add test for the pastIterations reducer.
> add tests for reducer/pastIterations.js

- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryAttachments.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryAttachmentsInfo.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDefault/index.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStorySection.js
- app/assets/javascripts/components/story/attachment/Attachment.js
- app/assets/javascripts/components/story/attachment/AttachmentList.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/stories.js
- app/assets/stylesheets/new_board/_story.scss
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/javascripts/components/story/expanded_story/attachment/attachment_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_attachments_spec.js
This PR changes the color of attachments button, from green to blue. I added too one dialog when one attachment is added but didn't save. Preview:
> Change color of attachments button.

- spec/javascripts/reducers/project_spec.js
We need tests for the reducers to maintain code quality.
This PR adds tests for reducer/project.js
> adds test for project.js reducer

- CHANGELOG.md
- [ V2 ] Drag-n-drop
- Bug when change release date of story.
- [ V2 ] When story is accepted and release it has a different background color.
> Update changelog to v2.6.0

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDescription/ExpandedStoryContentArea.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDescription/ExpandedStoryDescriptionEditButton.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDescription/ExpandedStoryDescriptionTextArea.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryDescription/index.js
- app/assets/stylesheets/new_board/_story.scss
- spec/javascripts/components/story/expanded_story/expanded_story_description/expanded_story_description_content_area_spec.js
> UX improvements in expanded story

- Dockerfile
- README.md
- docker-compose.yml
This PR updates the docker setup and fix some configs or package versions used.
Change list:
> Fix / docker setup update

- app/assets/javascripts/global_listeners.js
- app/assets/stylesheets/_cookie-banner.scss
- app/assets/stylesheets/_cookies-banner.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/shared/_cookies_banner.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/cypress/integration/cookiesBanner_spec.js
> Create LGPD cookies banner

- config/webpack/production.js
- package.json
- yarn.lock
The compilation was occurring because of 2 reasons, the first one was that compression-webpack-plugin needed a newer version of webpack, so we downgrade. And de second one, was that the @rails/webpacker major version 5, was creating an error when compiling on the Staging, so we downgrade this version too.
> Fix compilation error

- app/assets/javascripts/components/notes/Note.js
- app/assets/javascripts/components/story/StoryNotes.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_form.scss
- package.json
- spec/javascripts/components/notes/note_spec.js
- yarn.lock
> Convert note class component to functional component

- CHANGELOG.md
- Rails to 5.2.6.2
- Puma to 5.6.2
> Release v2.7.2

- app/controllers/application_controller.rb
- app/controllers/stories_controller.rb
- app/operations/base/activity_recording.rb
- app/operations/story_operations.rb
- app/operations/story_operations/legacy_state_change_notification.rb
- app/operations/story_operations/state_change_notification.rb
- app/services/gitlab/project_events_service.rb
- spec/operations/story_operations_spec.rb
- spec/services/gitlab/project_events_service_spec.rb
Refactor StoryOperations::Update to use [dry-monads](https://github.com/dry-rb/dry-monads) and [dry-matcher](https://github.com/dry-rb/dry-matcher), making use of variables and calls clearer.
Co-authored-by: Carlos Henrique https://github.com/carlospazuzu
> Refactor/StoryOperations::Update

- CHANGELOG.md
- Refactor Story operations to use dry-monads
> Release 2.7.3

- app/assets/javascripts/components/story/ExpandedStory/index.jsx
Convert the ExpandedStory component to be a functional component instead of a class
> Convert ExpandedStory to be a functional component

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryControls.jsx
Convert ExpandedStoryControls to be a functional component https://github.com/Codeminer42/cm42-central/issues/861
> Convert ExpandedStoryControls to be a functional component

- .github/pull_request_template.md
Creates a pull request template for the repository
Resolves https://github.com/Codeminer42/cm42-central/issues/884
> Create pull request template for the repository

- app/assets/javascripts/components/Markdown.jsx
- app/assets/javascripts/components/description/DescriptionContent.jsx
- package.json
- yarn.lock
Remove the memoizee package and replace to using React's memo functionallity
#912
> Replace memoizee package usage to React's memo

- package.json
- yarn.lock
Remove unecessary package glob
#913
> Remove unecessary package 'glob'

- app/assets/javascripts/components/notes/NoteForm.jsx
Updates NoteForm class into a function component.
> Refactor NoteForm class to function component

- README.md
1. Updates readme to set up using docker successfully
2. Also, this adds a new variable onto bash config to bootstrap this successfully on macos either
No issues
Follow up [this issue ](https://github.com/rails/rails/issues/38560)on github to know more about macos trouble
> Docs - update readme

- app/assets/javascripts/components/jquery_wrappers/AtWhoInput.jsx
- app/assets/javascripts/components/jquery_wrappers/Popover.jsx
- app/assets/javascripts/components/jquery_wrappers/TaggedInput.jsx
Updates jquery classes to function components
> Refactor jquery wrapper classes into function components

- app/assets/javascripts/components/forms/AsyncForm.js
Updates AsyncForm class into a function component.
> Refactor AsyncForm class to function component component

- app/assets/javascripts/components/projects/ProjectSearch.jsx
Updates ProjectSearch class into a function component.
> Refactor ProjectSearch class to function component

- app/assets/javascripts/components/story/StoryDatePicker.jsx
Updates StoryDatePicker class into a function component.
> Refactor StoryDatePicker class to function component
