Codeminer42/cm42-central

- .env.sample
- .gitlab-ci.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- app/controllers/integrations_controller.rb
- app/controllers/projects_controller.rb
- app/mailers/notifications.rb
- app/models/integration.rb
- app/models/project.rb
- app/models/story_observer.rb
- app/views/integrations/_form.html.erb
- app/views/integrations/index.html.erb
- app/views/notifications/started.text.erb
- app/views/projects/_form.html.erb
- app/workers/integration_worker.rb
- config/application.rb
- config/routes.rb
- db/migrate/20160818013050_create_integrations.rb
- db/schema.rb
- lib/integrations/mattermost.rb
- spec/controllers/integrations_controller_spec.rb
- spec/factories.rb
- spec/lib/integrations/mattermost_spec.rb
- spec/mailers/notifications_spec.rb
- spec/models/integration_spec.rb
- spec/models/story_observer_spec.rb
- spec/models/story_spec.rb
- spec/workers/integration_worker_spec.rb
First version of a simple integrations administration section in the Project details. It only has Mattermost right now, but it should simple enough to add more integrations later.
The code was inserted in the existing StoryObserver that already is used to send e-mail notifications. This could be refactored into a separated service later as well.
cc @daniloisr @adbatista
> Project Integrations for Outgoing Webhooks

- db/migrate/20160730022819_remove_default_username_from_users.rb
- db/schema.rb
User have a validation to prevent empty usernames, but the default was `''`. So our database had a lot of invalid users.
* This was preventing us to manage users, like adding them to a project.
* The code that fill usernames on production was a suggestion from @akitaonrails and we already ran it on our servers.
/cc @akitaonrails, @tiarly
> Add migration to prevent empty usernames

- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/screen.scss
Currently when you click on the estimate icon on the left side of the story:
You get an exception:
It happens because the's a listener for clicking there that should only be allowed for unestimated  stories. This PR fixes that listener and also fix some minor spacing issues inside the closed story view.
> Fix click on left estimate and story spacing

- app/assets/javascripts/models/story.js
In the server side, the accepted_at now is a date time, but the javascript part expected accepted_at to be just a date (equivalent to ‘beginning of day’) so stripping away the time part to make it work like before.
It was causing some projects to not open because the missingIteration function was trying to create a sprint with a startIteration number larger than the lastIteration number. And it was probably also causing iterations to finish earlier.
Stripping the time part should make the JS part work as before.
(WIP) check out the rest of the JS code to see other places using new Date(story.get("accepted_at")) and stripping the time part.
@rodrigovirgilio @adbatista
> Fixing the accepted_at datetime -> date in the javascript

- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
Fix the following exception:
```
PG::UniqueViolation - ERROR:  duplicate key value violates unique constraint "index_enrollments_on_team_id_and_user_id"
```
> Check if user belongs to team before adding him

- app/controllers/application_controller.rb
For some reason my `session[:locale]` is an empty string, what is preventing me from accessing the app.
```ruby
irb(main):001:0> '' || nil || :en
=> ""
```
> Prevent empty string being used as location

- app/mailers/notifications.rb
- app/operations/story_operations/member_notification.rb
- app/operations/story_operations/state_change_notification.rb
- app/views/notifications/accepted.text.erb
- app/views/notifications/delivered.text.erb
- app/views/notifications/rejected.text.erb
- app/views/notifications/started.text.erb
- config/environments/development.rb
- spec/mailers/notifications_spec.rb
- spec/operations/story_operations_spec.rb
After adding Sidekiq::Mailer on production all method call started to break because sidekiq pass arguments as json strings.
> Fix Notifications params with Sidekiq

- app/controllers/application_controller.rb
The `I18n.available_locales` returns an array of symbols, and it was expecting an array of strings.
> Fix bug with `set_locale`

- app/controllers/teams_controller.rb
- spec/controllers/teams_controller_spec.rb
When trying to update a team name with an empty value, the `@team` var was being set as `false` (which refers to the invalid update)
> Keep current team instance on edit action render when update fails

- app/assets/javascripts/views/story_view.js
- spec/javascripts/views/story_view_spec.js
When an attachment is uploaded, there is a cooldown between callbacks that if the story is saved, the form breaks. It should disable the control buttons of the history and only enable after the upload is fully completed.
> Disable control buttons during an attachment to a story

- app/controllers/teams_controller.rb
- app/views/layouts/application.html.erb
- config/routes.rb
The team link on header menu was sending to `teams#show` which was broken. This PR fix the link to send it to `teams#switch` and also remove the broken action `#show`.
> Fix team switching

- app/controllers/projects_controller.rb
- app/views/projects/import.html.erb
- spec/controllers/projects_controller_spec.rb
I've dealt with a few problems with the stories import...
- session[:import_job][:id] 
- session[:import_job][:created_at] was a string, which could not perform an operation needed to get how many minutes ago an import job was created
- when dealing with a list of stories that were never accepted the import was not working
> Fix stories import

- app/assets/stylesheets/_animations.scss
- app/assets/stylesheets/_flash-message.scss
- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/_navbar.scss
- app/views/application/_flash.html.erb
The flash messages were in a relative positioned container causing it to push down the page content.
Also, closing the notification would lead to a blank space and break a few pages layout.
> Improve flash notifications design

- app/assets/javascripts/views/project_view.js
- app/assets/stylesheets/_form.scss
- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/_project-settings.scss
- app/assets/stylesheets/_screen.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/form.scss
- app/views/integrations/index.html.erb
- app/views/projects/_form.html.erb
- app/views/projects/_share_form.html.erb
- app/views/projects/_transfer_form.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/import.html.erb
- app/views/projects/new.html.erb
- spec/features/keycut_spec.rb
- spec/features/stories_spec.rb
- spec/support/integration_helpers.rb
There were a couple recurrent tests failing the builds. Apparently, adding the line `first('.column_header').click` was able to allow the page to load and the tests to pass more frequently. 
Increasing the `Capybara.default_max_wait_time` was not making any difference.
> New Project page redesign

- CHANGELOG.md
- app/assets/javascripts/global_listeners.js
- app/assets/stylesheets/_navbar.scss
- app/assets/stylesheets/_project-reports.scss
- app/assets/stylesheets/_screen.scss
- app/assets/stylesheets/application.scss
- app/controllers/locales_controller.rb
- app/helpers/projects_helper.rb
- app/views/devise/passwords/edit.html.erb
- app/views/integrations/index.html.erb
- app/views/layouts/application.html.erb
- app/views/projects/edit.html.erb
- app/views/projects/import.html.erb
- app/views/projects/reports.html.erb
- app/views/registrations/edit.html.erb
- app/views/teams/index.html.erb
- app/views/users/index.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
> Edit password and Project reports page

- app/assets/javascripts/views/project_view.js
- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/_project-settings.scss
- app/assets/stylesheets/_screen.scss
- app/views/teams/_form.html.erb
- app/views/teams/new.html.erb
The Project Settings pages like Import and Integrations which have a smaller height than screen size were broken.
- Fix  the pages below giving `.main` and `.container-fluid` a `height:100%`  so the `.settings-page` can follow their height.
- Add borders on `.storycolumn`, so it matches the `.column_header` size.
- Add redesign to New Team page
> Fix positioning problems on Project Settings page

- app/assets/javascripts/views/story_view.js
Story views were getting the current location from  `window.location`. Having a current location ending with `#story-<id>` or `#`, would cause `.story-link-` to have a broken link.
This PR add a function to Story view to check if there are any ids at the current location and removes them before providing it to the `.story-link-`.
> Remove id when getting location on story view

- CHANGELOG.md
- app/assets/stylesheets/_form.scss
- app/assets/stylesheets/_users.scss
- app/views/admin/users/_form.html.erb
- app/views/admin/users/edit.html.erb
- app/views/admin/users/index.html.erb
- app/views/teams/edit.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
This PR add a couple pages under `admin_user` routes redesign, which were missing from #62.
> Admin Users redesign

- app/api/entities/integration.rb
- app/api/entities/project.rb
- spec/api/entities/integration_spec.rb
When queried a particular project, it now returns the integrations corresponding to the project.
> Add integrations to Project endpoint

- CHANGELOG.md
- app/assets/javascripts/views/column_view.js
This PR fix a bug from #118 which would not allow an user to move an Story from a column to another.
> Stories drag and drop bugfix

- app/assets/stylesheets/_screen.scss
In a display with medium size, the projects is differing its height causing the grid to not align.
> Fix Projects display alignment

- CHANGELOG.md
- app/assets/javascripts/templates/alert.ejs
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_simple-alert.scss
- config/locales/en.yml
- config/locales/es.yml
- config/locales/pt-BR.yml
- spec/javascripts/views/story_view_spec.js
When a Story's attachment upload fails. There was no event notifying
the StoryView that the upload had already finished. So, the
save/delete/cancel buttons would stay disabled until a new attachment
upload had been successfully completed.
> Fix bug that keeps save/cancel buttons disabled after a failed upload

- CHANGELOG.md
- db/migrate/20170407114148_increase_position_decimal_precision_to_stories.rb
- db/schema.rb
This PR fixes https://github.com/Codeminer42/cm42-central/issues/144
The decimal precision from stories position wasn't enough for some positions(13 numbers after the decimal point).
ex: `12.62582043025265` was rounded to `12.6258204302527`
> Increase decimal precision from Stories position

- CHANGELOG.md
- app/assets/javascripts/components/stories/StoryLink.js
- app/assets/javascripts/components/story/StoryDescription.js
- app/assets/javascripts/views/form_view.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_screen.scss
- package.json
- spec/features/stories_spec.rb
- spec/javascripts/components/stories/story_link_spec.js
- spec/javascripts/components/story/story_description_spec.js
- spec/javascripts/views/story_view_spec.js
Stage 1 of #81 
Stories in the same Project can now be referenced on another story's
description. A new parser was added on the StoryView to intercept and
turn '#<story_id>' into links which would later turn into StoryLinkViews
providing the current state of the story.
**New icons look**
> Local story links

- CHANGELOG.md
- app/api/entities/project.rb
- spec/features/keycut_spec.rb
- spec/rails_helper.rb
- spec/support/cleaner.rb
This PRs do some fixes as:
- Remove the API module used in `using` params into Project Entity
- Clean up DatabaseCleaner config
> Some fixes for DatabaseCleaner and Travis

- CHANGELOG.md
- app/views/projects/reports.html.erb
Fix #164 
There was a typo preventing an correct translation to 'Velocity per member' report at the Reports page.
> Fix typo preventing translation on reports page

- CHANGELOG.md
- app/assets/stylesheets/_screen.scss
When adding a note or a task, the throbber.gif was not displayed, as it was requested without the hash, triggering a 404 in a production configuration.
This PR fixes that by ensuring that the hash of the `throbber.gif` is included when the CSS is generated.
> Fix CSS link to throbber.gif when adding a note or a task

- CHANGELOG.md
- app/assets/javascripts/components/story/StorySelect.js
- app/assets/javascripts/views/story_view.js
- Creates a StorySelect react component to provide an generic component to select story estimate, type and state.
- Uses `StorySelect` to handle story estimate.
> Add story estimate react component 

- app/assets/javascripts/templates/activity.ejs
- app/assets/stylesheets/_screen.scss
Changes story activity related CSS class names prefix from `.activity` to `.story-activity` in
order to fix a class name conflict with elements from PR #156.
> Fix story activity CSS class name conflicts

- CHANGELOG.md
- Gemfile.lock
- README.md
- app.json
- app/operations/story_operations/state_change_notification.rb
- app/views/integrations/_slack.html.erb
- app/workers/integration_worker.rb
- spec/controllers/integrations_controller_spec.rb
- spec/operations/story_operations_spec.rb
- spec/workers/integration_worker_spec.rb
Added slack integration. The messages are sent to the channel with the format below.
If Mattermost and Slack are configured the text will be sent to both services. This depends on a PR in [cm42-central-support](https://github.com/Codeminer42/cm42-central-support/pull/6).
> Added slack integration

- CHANGELOG.md
- package.json
- Move "babel-preset-airbnb" outside devDependencies in package.json
> [hotfix: 1.4.1] Move babel-preset-airbnb to dependencies in package.json

- CHANGELOG.md
- app/assets/javascripts/templates/column.ejs
- app/assets/javascripts/templates/project_view.ejs
- app/assets/javascripts/views/column_view.js
- app/assets/javascripts/views/history_view.js
- app/assets/javascripts/views/project_view.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_screen.scss
- spec/javascripts/views/column_view_spec.js
There was a bug causing a HistoryView to duplicate itself when actions where triggered by another stories
* HistoryView was refactored while fixing the bug and should now be able to update itself when an change occurs on its story.
> Fix Story History bug

- CHANGELOG.md
- Story History is now able to listen for changes on the story
- Codeclimate file with engines and removed files from analysis
- Story type select to react component
- Story state select into react component
- Story requested_by select to react component
- Move select components to renderSelects function
- Story owned_by select to react component
- Alter route button Manage Members Team and associate user in team
- Story notes into react components
- Story labels to react component
- Story History bug when story actions where triggered
- Ticket not being reassigned to current user when state change to "started"
> [1.5.0] 2017-06-23

- CHANGELOG.md
- app/policies/user_policy.rb
- spec/policies/user_policy_spec.rb
i think don't make sense in action create verify is_himself.
> #191 - fix action create in user_policy

- CHANGELOG.md
- spec/javascripts/components/tasks/task_form_spec.js
The spec was trying to access the state of a child component, which it is not possible. So we changed to check if the component has the selector `.saving`
cc: @IgorVieira , @leonardofreitass
> Fix 'stop loading when save' spec

- CHANGELOG.md
- Changing `webpack-rails` gem to new `webpacker` gem
> Release v1.9.0

- CHANGELOG.md
- Allowed params to update project via API
- Fix central manage login and logout bugs
- Don't show projects to guests that he's not member of
- Disallow guests to make changes on projects
> Update CHANGELOG to 1.10.0

- CHANGELOG.md
- Gemfile.lock
Fixes #264 
---
...but also points out another issue on velocity: 
The frontend always use the last 3 iterations with one or more done stories to calculate the velocity. If, for an example, there are no stories on the past iteration and the one before it, it will still use the ones before them until there is 3 iterations with at least one accepted story each (or unless it realizes there are less than 3 iterations). This logic is on `app/assets/javascripts/models/project.js`.
The backend, however, will only look for done iterations on the past month. If there is less than three iterations on the last month, it will not even look for the past stories. This logic is encapsulated on `IterationService` class on central-support gem, and evoked at `ProjectPresenter#velocity`.
It should be noted …
> Update central-support gem

- CHANGELOG.md
- Gemfile.lock
- app/assets/javascripts/models/project.js
- app/presenters/project_presenter.rb
The velocity calculation for the projects was wrong, it was not considering empty iterations as explained in #266
Solves #266
> Fix projects velocity calculation

- CHANGELOG.md
- app/assets/javascripts/templates/project_view.ejs
- app/assets/javascripts/templates/story.ejs
- app/assets/javascripts/views/project_search_view.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_form.scss
- app/assets/stylesheets/_screen.scss
- spec/features/stories_spec.rb
Changes how the `search results` column works now to add the option so the user can drag stories from there into the other columns. Also add the option to find the actual story on click at the search result story. in accord to the issue #263 moved from #256
---
> Adds the option to drag stories from the search results.

- Dockerfile
- docker-compose.yml
- Changed the path to the local node_modules folder. This way, the
mapping between the container and the host will work.
- Removing the redis-server from the Dockerfile, since it's been used in
a separated container.
> Fix folder mapping on docker compose

- CHANGELOG.md
- app/assets/javascripts/views/project_view.js
Fix the bug causing the search results to vanish from the search results column after dragging a story from one column to another.
> Fixes search results column being cleared

- CHANGELOG.md
- app/assets/javascripts/views/project_view.js
- app/assets/javascripts/views/story_view.js
Reverse the order which stories appear within the `Chilly bin` column, in accord with the request on #269. Causing the newly created stories to appear on top.
> Inverts the stories order in the chilly bin column

- CHANGELOG.md
- README.md
- docker-compose.yml
- Adding nginx-proxy service: with this service setup on the project, we
can use custom domain names while developing locally, avoiding local
ports collision if we already have other app using the port 3000.
- Adding adminer image: added this image to be a quick way to explore
the postgres database, without needing to setup other external tools.
> Improvements to docker-compose

- CHANGELOG.md
- Added adminer service to docker-compose.
- Added nginx proxy to docker-compose, to enable us to use custom domain names on development.
- Changes on the style of the estimation form, on a story card.
- Changes the order which stories appear in the chilly bin column
- Show the form to estimate a task without having to open it
- Search results column being cleared after dragging a story between columns
- Search results wrongly appearing during searches 
- Updated "central-support" gem to fix the volatility calculation.
> Update CHANGELOG to v1.14.0

- CHANGELOG.md
- app/assets/javascripts/components/tasks/Task.js
It solves the bug pointed here: https://github.com/Codeminer42/cm42-central/issues/289
Now:
> Fixes the task's label character escaping

- CHANGELOG.md
- app/controllers/stories/activities_controller.rb
- spec/controllers/stories/activities_controller_spec.rb
There was a bug, which was preventing project members to see a story's activities.
> Fixes activities controller to correctly sets current_project to ActivityScope

- CHANGELOG.md
- Added the option to clone a story.
- Updated central-support gem version, so Slack can be used in integrations here now.
- Updated central-support gem version, to fix story cache_names bug when it was removed
- Tasks labels aren't escaping special characters anymore.
- Activities from a story is now showing correctly to non-admins project members
> Update CHANGELOG to v1.15.0

- app/assets/javascripts/components/stories/Iteration.js
- app/assets/javascripts/templates/iteration.ejs
- app/assets/javascripts/views/iteration_view.js
- app/assets/javascripts/views/project_view.js
- app/assets/javascripts/views/story_view.js
- app/assets/stylesheets/_screen.scss
- spec/javascripts/views/iteration_view_spec.js
Changes the way the iterations are handled in the 'done' column, having them previous iterations load collapsed, with only the current one expanded. Fixes #285
> Collapsed iterations

- CHANGELOG.md
- Auto collapse done stories.
- Ability to drag stories from the epic column.
- Updated rails to 4.2.7.1
- Updated rubocop to 0.49.1
- Webpack manifest host path set to localhost, so webpack pack file load on Windows is fixed
- Highlight the searched stories not behaving properly.
> Update CHANGELOG to v1.16.0

- CHANGELOG.md
- app/controllers/projects_controller.rb
- package.json
- yarn.lock
- Add jquery-ui to fit cloudinary-js missing dependency
- Preload tag_group in projects query on projects controller
> Fix projects controller

- CHANGELOG.md
- Add jquery-ui to fit cloudinary-js missing dependency
- Preload tag_group in projects query on projects controller
- Sort all stories in backlog to keep intended priority
> Update to 1.16.1

- CHANGELOG.md
- Adjusted README to use yarn install instead npm install on project setup
- Remove auto scroll to bottom when adding a story and highlights it instead
- Fix a bug in stories movement, now this action doesn't select the stories texts
- Update attachinary options before it gets invalid.
- Moved the story estimate buttons to a react component.
> Update CHANGELOG to v1.17.0

- CHANGELOG.md
- README.md
- app/controllers/projects_controller.rb
- app/views/projects/import.html.erb
- spec/controllers/projects_controller_spec.rb
1. Changes
- Change field to import from attachinary_file_field to file_field
1. Why
- The JS fileupload have some conflit, or loading in wrong place, and this way the name from archive that the user do a upload dont appear, it is one way that can do this solution.
> Altered form to import a file, because conflit js

- CHANGELOG.md
- app/assets/javascripts/models/story.js
Why this PR?
- When you tried create a story, and you failed, the first failed you see the error, but if you click em create again, so your screen become freeze, and refresh the page is necessary.
> Fix freeze screen when save story

- CHANGELOG.md
- Update attachinary options before it gets invalid.
- Added memcached service to docker-compose, now action import work well
- Change in import project, switch button attachinary_file_field to file_field
- Change the verification to refuse if const files is null, otherwise return the value files
- Request signature for file uploads once and all stories get this from a global place
> Update CHANGELOG to v1.18.0

- config/initializers/monkey-patchs.rb
- lib/actionpack_extensions/action_dispatch/request/utils.rb
- spec/controllers/stories_controller_spec.rb
Deep munge was introduced to keep query generation safe. This patch applies
the behaviour present in Rails 5.0 and 5.1. For a broader discussion see
rails/rails#13420
> Don't convert empty arrays to nil

- CHANGELOG.md
- Gemfile
- app/controllers/stories_controller.rb
- app/models/iterations/past_iteration.rb
- app/models/iterations/project_iterations.rb
- app/operations/iteration_operations.rb
- app/operations/story_operations.rb
- spec/controllers/stories_controller_spec.rb
- spec/models/iterations/past_iteration_spec.rb
- spec/operations/iteration_operations_spec.rb
- spec/operations/story_operations_spec.rb
It was full of N+1 queries, and letting the things very slow
> Refactor PastIteration mounting process

- CHANGELOG.md
- app/assets/javascripts/components/projects/ProjectCard.js
- app/assets/stylesheets/_members.scss
- app/serializers/project_serializer.rb
- spec/javascripts/components/projects/project_card_spec.js
- spec/serializers/project_serializer_spec.rb
When taking the `/teams` route, after selecting your team and depending on how many projects you have on that team, the load time was taking too long (more than a minute in some cases), causing a timeout.
This PR intends to accelerate this load considerably by removing the volatility / velocity from the ProjectCard, since there is no real need to have it being shown there and it makes the page load in less than 5s.
> Fix the load speed of projects after choosing a team

- app/assets/javascripts/actions/column.js
- app/assets/javascripts/components/Columns/ColumnItem.js
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/components/stories/Sprints.js
- app/assets/javascripts/models/beta/iteration.js
- app/assets/javascripts/reducers/columns/backlog.js
- spec/javascripts/components/stories/sprints_spec.js
- spec/javascripts/reducers/column_backlog_spec.js
[Task link ](https://central.cm42.io/projects/central-board-v2#story-22527)
The group by sprints was being done directly in the component, now is store responsibility.
> Group by sprints directly in the store

- CHANGELOG.md
- app/assets/javascripts/pusherSockets.js
@talyssonoc requested to refactor pusherSockets to prevent errors when pusher env vars were empty.
Also, I removed some constants from general scope and moved them to functions where they were used and added as parameters on another functions.
> refactor pusherSockets and allow pusher env vars to be empty

- CHANGELOG.md
- app/assets/javascripts/views/column_view.js
As reported on the issue #353 , the text inside a story note was not selectable.
Adding `.story-description`, `.notes` and `.form-control` to `cancel` elements prevents the `drag n' drop` event from triggering, consequently, allowing the text inside the element to be selected.
> added story description and notes to sortable canceled elements

- CHANGELOG.md
- app/models/iterations/project_iterations.rb
- spec/factories/project_factory.rb
- spec/models/iterations/project_iterations_spec.rb
- spec/operations/story_operations_spec.rb
Fix calculation of first sprint size when the project start date differs of iteration start date.
- Change the calculate to use iteration start date instead of project start date
> Fix calculation of first sprint size

- CHANGELOG.md
- app/models/note.rb
- app/models/task.rb
- spec/models/note_spec.rb
- spec/models/task_spec.rb
When trying to destroy a project, and that one has a story already accepted with tasks or notes was accusing the error `ActiveRecord::ReadOnlyRecord`.
- Override the method `readonly?` instead of delegate to story, to accept be destroyed by association.
> Fix project delete 

- app/models/iterations/past_iteration.rb
- app/models/iterations/project_iterations.rb
- app/models/story.rb
- app/operations/iteration_operations.rb
- db/seeds.rb
- spec/models/iterations/project_iterations_spec.rb
- spec/models/story_spec.rb
- spec/operations/story_operations_spec.rb
- Remove stories property in past_iterations when calling it for the first time.
- Refactor iteration model and operation
modified:   app/models/iterations/past_iteration.rb
modified:   app/models/iterations/project_iterations.rb
modified:   app/models/story.rb
modified:   app/operations/iteration_operations.rb
> Remove unnecessary response with stories in past iterations

- CHANGELOG.md
- app/assets/javascripts/pusherSockets.js
- Add fallback to long polling when pusher API key is missing.
Reference: [#400](https://github.com/Codeminer42/cm42-central/issues/400)
> Fallback to long polling

- app/assets/javascripts/components/projects/ProjectCard.js
- spec/javascripts/components/projects/project_card_spec.js
It was necessary to decode HTML entities to appear the right content.
Ref: [#story-23199](https://central.cm42.io/projects/central#story-23199)
Before
After
> Fix special character in project title

- CHANGELOG.md
- Added supports to upload libre office formats
- Imports/exports of stories 
- Documents
- Tasks
- Added Popover when Story is collapsed in board V2
- Resouce to expand/collapse a story in board V2
- Button to copy story url to clipboard in board V2
- Change estimate button to dynamic values when story is collapsed in board V2
- Fix imports notes of stories
- Fix project delete when tasks or notes are readonly
- Fix exporting unnecessary fields from documents and done to export in JSON
- Fix pusher missing api key
- Special character in project title
- Updated rails from 4.2.7.1 to 4.2.11 (CVE-2018-16476)
- Updated rack from 1.6.10 to 1.6.11 (CVE-2018-16471)
- Updated loofah from 2.2.2 to 2.2.3 (CVE-2018-16468)
- Updated nokogiri from 1.8.4 to 1.8.5 (CVE-2018-14404
and CVE-2018-14567)
- …
> BUMP CHANGELOG to 1.22.0

- app/controllers/notes_controller.rb
- app/controllers/stories_controller.rb
- app/controllers/teams_controller.rb
- config/initializers/csv_renderer.rb
- spec/features/notes_spec.rb
- spec/features/teams_spec.rb
When there was an attempt to create a team with invalid parameters (e.g., without a name or with an already existing name), it should return a message explaining what the error was, but all that was returning was a generic error without any description.
With the changes made on `teams_controller.rb` the view can receive proper information to return to the user and describe what the problem was.
> Now an error returns when a team is created wrongly

- CHANGELOG.md
- [ V2 ] Story:
- Title;
- Type;
- Requested By;
- Owned By;
- Estimate;
- Description;
- State;
- Save, Cancel and Delete;
- Notes;
- Tasks;
- Labels;
- [ V2 ] Refactor Redux flow to remove stories duplication
- Bug on unarchive projects
- Wrong serialization in JSON
- Amount of backlog points in reports page
- Bug on creating two teams with the same name
- Package: camelcase-object-deep: 1.0.7 to change-object-case: 0.2.0
- Due to the update of the recaptcha gem, changed recaptcha's ENV variable names from `PUBLIC_KEY` and `PRIVATE_KEY` to `SITE_KEY` and `SECRET_KEY` respectively.
- Package: sinon: 1.17.5 to 2.0.0
- Ruby from 2.3.1 to 2.6.0
- Rails from  4.2.11 to 5.2.1
> Update changelog to v2.0.0

- app/assets/stylesheets/new_board/_story.scss
Small adjustment made to collapsed stories on central v2. Now the labels are displayed underneath the title. Here's how it looked before: 
And how it looks now:
> labels are now displayed under the collapsed story title

- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/new_board/_column.scss
- app/assets/stylesheets/new_board/_project_board.scss
- app/assets/stylesheets/new_board/_story.scss
Fixed the project page on v2 where scrolling wasn't possible (which is normally needed when expanding a story), and fixed small bug where the check boxes from the tasks in an expanded story were misplaced. Here's how it looks now:
> Fixed task checkboxes and scrolling on project in v2

- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryNotes.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryTask.js
- app/assets/javascripts/views/story_view.js
- spec/javascripts/components/story/expanded_story/expanded_story_notes_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_task_spec.js
- spec/javascripts/views/story_view_spec.js
When a note or task is being added to a story, the add button is disabled until the user adds any text to the text area. These changes were made on both versions of Central (v1 and v2). Here's an example:
> prevent empty tasks and notes from being added on both v1 and v2

- CHANGELOG.md
- Front-End Dependencies
- Webpack from 2.6.1 to 4.29.1
- React from 15.4.2 to 16.8.0
- Redux from 3.7.2 to 4.0.1
- Babel from 6.25.0 to 7.2.2
- Test Dependencies
- Enzyme from 2.7.1 to 3.8.0
- Jasmine from 2.5.1 to 3.3.0
- Karma from 1.3.0 to 4.0.0
- Sinon from 2.0.0 to 7.2.3
- [ V2 ] Board style to permit scrolling
- Fix alert favicon in production environment
- Export projects with no stories
- [ V2 ] Story:
- Attachments:
- With this change makes it necessary to set unsigned upload in cloudinary and set the ENV `CLOUDINARY_UPLOAD_PRESET`. For help you can see [this](https://cloudinary.com/documentation/upload_images#unsigned_upload) tutorial.
> Release v2.1

- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/story/CollapsedStory/CollapsedStoryEstimateButton.js
- app/assets/javascripts/components/story/CollapsedStory/CollapsedStoryStateActions.js
- app/assets/javascripts/components/story/CollapsedStory/CollapsedStoryStateButton.js
- app/assets/javascripts/components/story/CollapsedStory/index.js
- app/assets/javascripts/components/story/ExpandedStory/ExpandedStoryAttachments.js
- app/assets/javascripts/components/story/attachment/AttachmentList.js
- app/assets/javascripts/models/beta/story.js
- spec/javascripts/actions/story_spec.js
- spec/javascripts/components/story/collapsed_story/collapsed_story_spec.js
- spec/javascripts/components/story/collapsed_story/collapsed_story_state_button_spec.js
- spec/javascripts/models/beta/story_spec.js
Now we can change the estimation and state of a closed story.
stories:
- [#23440](https://central.cm42.io/projects/central-board-v2#story-23440) (Estimate)
- [#23481](https://central.cm42.io/projects/central-board-v2#story-23481) (State)
It closes [#512](https://github.com/Codeminer42/cm42-central/pull/512).
> Feature/ update collapsed story

- app/assets/javascripts/models/beta/iteration.js
- app/assets/javascripts/selectors/backlog.js
- app/assets/javascripts/selectors/columns.js
- spec/javascripts/models/beta/iteration_spec.js
* The velocity used to alocate stories to sprints, using the avarage points from the last 3 sprints
* If there ir less than 3 past sprints, the velocity should receive its default
* When there are at least 3 previous sprints the velocity receives the avarage points from the last 3 sprints
* using default velocity 3
* using relative velocity 24
> Relative velocity

- CHANGELOG.md
- app/controllers/beta/projects_controller.rb
- app/views/beta/projects/show.html.erb
Add the project navigation bar links in the v2 board.
Obs: currently the links will redirect to the v1 but in the future when the v2 get done the links will work as they should.
> Project navbar links v2

- CHANGELOG.md
- [ V2 ] Remove redundant switch cases from the stories reducer.
- [ V2 ] Fix number, date and points of sprints.
-  [ V2 ] Sprints are shown in easier order in "done" column
- [ V2 ] Add project navigation bar
- [ V2 ] Fetch and show stories on the done column
- [ V2 ] Story:
- Stories of release type
- Option to Clone Stories
- Disable fields when story is read-only
- Link directly to stories
- History
- [ V2 ] Centralized notification system
- [ V2 ] Top nav
> Update changelog to 2.3.0

- CHANGELOG.md
- app/assets/javascripts/models/beta/column.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/selectors/done.js
- app/operations/story_operations.rb
- app/operations/story_operations/state_ensurement.rb
- spec/features/stories_spec.rb
- spec/javascripts/models/beta/story_spec.js
- spec/operations/story_operations/state_ensurement_spec.rb
- spec/operations/story_operations_spec.rb
Before os this PR, one story with unscheduled state should not had estimate, now one story with unscheduled state may or may not have estimate, so with this changes in chilly bin column the stories can be estimate.
> Change chilly bin rule

- app/api/entities/project.rb
- app/api/v1/projects.rb
- app/services/iteration.rb
- spec/services/iteration_spec.rb
This is the migrating the iteration service class from cm42-central-support to cm42-central.
> Migrate iteration service from support

- app/services/integrations/discord/helper.rb
- app/services/integrations/discord/service.rb
- app/workers/integration_worker.rb
- spec/services/discord_service_spec.rb
This pr is migrating the Discord class and DiscordHelper tests, from cm42-central-support to cm42-central.
> Migrate Discord from cm42-central-support

- app/models/iteration.rb
- spec/models/iteration_spec.rb
This is the migrating the Iteration model from cm42-central-support to cm42-central.
> Migrate Iteration model from support

- CHANGELOG.md
- Rewire and Rewire Webpack
- Inject loader
- Karma and all dependencies related
- [ V2 ] When story is accepted it has a different background color.
- Unscheduled stories may or not may have a estimate.
- Chilly Bin column have stories with or no estimate.
- Migrate all the javascripts tests from jasmine to jest.
- Front-End Dependencies
- NodeJS from 9.11.2 to 10.17.0
- Webpack Dev Server from 3.1.14 to 3.9.0
- babel-jest and @testing-library/jest-dom
- [ V2 ] Dialog confirmation when story state is changed in expanded shape.
- [ V2 ] Spinner when project is loading.
- [ V2 ] User mention.
- [ V2 ] Button to reverse story flow.
- [ V2 ] Actor in history of changes.
- [ V2 ] Buttons to show and hide columns.
- [ V2 ] Internationalization date.
- [ V2 ] Sprints calc bug.
> Changelog to 2.5.0

- CHANGELOG.md
- package.json
- yarn.lock
This PR fixes the bug of release date. When `react-datepicker` was update to new version, the `datepicker` of V1 was broken because the old version accepts only `string` in Datepicker component, and new version accepts an `Date Object`, so for datepicker works, was needed to regress the version.
> Regress datepicker version

- CHANGELOG.md
- app/assets/javascripts/actions/actionTypes.js
- app/assets/javascripts/actions/story.js
- app/assets/javascripts/components/projects/ProjectBoard.js
- app/assets/javascripts/models/beta/projectBoard.js
- app/assets/javascripts/models/beta/story.js
- app/assets/javascripts/reducers/stories.js
- app/controllers/beta/stories_controller.rb
- app/models/story.rb
- app/policies/story_policy.rb
- app/services/beta/sort_stories.rb
- config/routes.rb
- db/migrate/20210201140311_add_new_position_to_story.rb
- db/schema.rb
- lib/tasks/populate_newposition.rake
- spec/cypress/integration/dragAndDrop_spec.js
- spec/cypress/support/commands.js
- spec/javascripts/actions/story_spec.js
- spec/javascripts/models/beta/project_board_spec.js
- spec/javascripts/models/beta/story_spec.js
- spec/javascripts/selectors/backlog_spec.js
- spec/models/story_spec.rb
- spec/rails_helper.rb
- spec/requests/beta/stories_controller_spec.rb
**DESCRIPTION**
A new sorting logic has been implemented, due to the problems caused by the float limitations in relation to the number of decimal places, which affected the scalability of the old method. Then an algorithm was implemented that will add 1 to the modified story and to all in front of it.
**CHANGELOG**
- Created a column called "new_position" to all stories
- A script to populate it - `bundle rake populate_newposition` to run
- Created a new route to update stories with this method - `/beta/sort`
- Created specs in backend
- Change sort logic in frontend
- Update specs in frontend
> New position logic for drag and drop beta version

- .babelrc
After running jest, babel showed warning about the option uglify that became deprecated and changed to forceAllTransforms, and corejs that wasn't defined, so babel assumed that was version 2, but there are already version 3, so will be more obvious and protect the code if we define it's version, and the version described on package.json was version 2.
Babel warnings that was fixed:
Link for the doc
core-js: https://babeljs.io/docs/en/babel-preset-env#corejs
forceAllTransforms: https://babeljs.io/docs/en/babel-preset-env#forcealltransforms
> Fix babel warnings about deprecated options

- app/services/remove_stories_from_user_service.rb
- spec/controllers/users_controller_spec.rb
Admins weren't able to remove users from projects when said user owned an accepted story. The PR fixes this issue by addressing this condition on the service that handles the user removal.
> fix: remove user membership when he owns an accepted story

- app/controllers/application_controller.rb
- app/controllers/stories_bulk_update_controller.rb
- app/operations/story_operations.rb
- spec/controllers/stories_bulk_update_controller_spec.rb
- spec/operations/story_operations_spec.rb
Refactor StoryOperations::UpdateAll to use [dry-monads](https://github.com/dry-rb/dry-monads) and [dry-matcher](https://github.com/dry-rb/dry-matcher), making use of variables and calls clearer.
> Refactor/StoryOperations::UpdateAll

- app/controllers/project_boards_controller.rb
- app/operations/beta/project_board_operations.rb
- app/operations/story_operations.rb
- spec/operations/beta/project_board_operations_spec.rb
- spec/operations/story_operations_spec.rb
Refactor StoryOperations::ReadAll to use [dry-monads](https://github.com/dry-rb/dry-monads) and [dry-matcher](https://github.com/dry-rb/dry-matcher), making use of variables and calls clearer.
> Refactor/StoryOperations::ReadAll

- spec/javascripts/components/story/collapsed_story/collapsed_story_actions_spec.js
- spec/javascripts/components/story/collapsed_story/collapsed_story_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_controls_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_default/expanded_story_default_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_description/expanded_story_description_content_area_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_description/expanded_story_description_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_estimate_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_history_location_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_labels_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_notes_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_owned_by_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_release/expanded_story_release_date_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_requested_by_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_section_spec.jsx
- spec/javascripts/components/story/expanded_story/expanded_story_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_state_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_task_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_title_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_tooltip_spec.js
- spec/javascripts/components/story/expanded_story/expanded_story_type_spec.js
Migrate unit tests in `components/story/expanded_story` from Enzyme to testing-library
#908 
N/A
Working with @wrspada02 , merged some of his upstream changes into it before opening PR
> migrate components/story/expanded_story tests from Enzyme to testing-library

- Gemfile
- Gemfile.lock
- app/views/devise/sessions/new.html.erb
- spec/features/confirmations_spec.rb
- Our CI had some broken tests due to the ChromeDriver version in the Ubuntu image. This is a [known issue](https://github.com/teamcapybara/capybara/issues/2800) for the Capybara gem.
The community is suggesting a gem that syncs Capybara commands with the JS: https://github.com/makandra/capybara-lockstep
> Fix: Broken CI tests 
